### ISSUE TITLE
Put terms of services https://www.shopify.ca/tools/policy-generator/terms-and-conditions

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-main#32]
Welcome to UnivJobs, operated by DCommons, Inc. (“UnivJobs” and sometimes referred to as “our”) and located at 2035 Sunset Lake RoadSuite B-2, 19702, Newark, Delaware  Thank you for using or visiting our products and services (“Services”). Our Services are a platform through which current and former students at particular educational institutions seeking employment opportunities or contracting opportunities (each, a “Student”) can find and connect with providers of such employment or contracting opportunities (each, a “Business”).

UnivJobs does not take part in, nor is DCommons, Inc in any way responsible for, any interactions between Students and Businesses, except to the extent necessary to maintain our Services. Any interaction between you and any other individual or entity through our Services or arising out of your use of our Services, including any interactions between Businesses and Students, is solely between you and that other individual or entity. UnivJobs expressly disclaims any responsibility for any interactions between Students and Businesses. For avoidance of doubt, UnivJobs disclaims any responsibility for any employment or contracting opportunities, employment or contracting services, or any other services or products acquired or made available through our Services, even if UnivJobs investigates or attempts to verify any information in connection therewith. You agree that you must evaluate and bear all risks associated with the use of our Services, including the Services Materials and the User Content, and that you may not rely on the Services Materials or User Content.

The following terms and conditions (“Terms”) govern your use of our Services. These Terms are deemed to include all other operating rules, conditions, policies and procedures that are referred to herein or that may otherwise be published by UnivJobs from time to time ("Policies"), at our website or via any App (including without limitation, our Privacy Policy). By accessing, viewing, or using our Services, you indicate that you have read and understand these Terms, that you agree to them and intend to be legally bound by them. If you do not agree to these Terms, or if you are under 18 years of age, or if you are not a legal resident of the Canada, you are not granted permission to use our Services and must exit immediately.

1. ) **Registration.** In order to access certain content, services, products or benefits on our Services, you will be asked to register and create an account. By registering an account on our Services, you represent that you are 18 years of age or older. Depending on your intended uses of our Services, you may be asked to designate your account as either a Student Account (i.e., for a Student) or a Business Account (i.e., for a Business). Your obligations and rights under these Terms may vary depending on whether you registered as a Student or a Business. Also as part of the registration process, you may be asked to select a username and password, and may be required to provide UnivJobs with certain information about yourself, including some types of personally identifying information such as your email and postal addresses, your telephone number and your employer or educational institution. You agree that the information that you provide to us on registration and at all other times will be true, accurate, current and complete. You also agree that you will ensure that this information is kept accurate and up to date at all times. Any information that you provide to UnivJobs through our Services or email is subject to UnivJobs' Privacy Policy, which is hereby incorporated into these Terms by reference as if set forth fully herein.

As part of the registration process, you will be asked to select a user name and password. Only you are permitted to access our Services, the Services Materials, and the User Content through your account. Without limiting the foregoing, you are fully responsible for your account, including use of the account by any third party, and maintaining the confidentiality of your password. You may suspend your account at any time by suspending the account within your profile or by emailing univjobs@gmail.com.

By registering, you are subscribing to transactional notification emails and/or text messages related to the Services (including notifications that will inform you when a job that matches your profile is posted). You can unsubscribe or manage your notification frequency settings at any time by logging into your account and changing your notification settings or by using any of the other methods described in the Privacy Policy.

2.)**Verification**. By registering with our Services, you hereby authorize UnivJobs to verify any representations and warranties you make either pursuant to these Terms or within any materials submitted during the registration process, including conducting background checks, contacting any provided references, and reviewing public records. You acknowledge that while UnivJobs reserves the right to verify these representations and warranties, UnivJobs is not obligated to do so, and may choose not to do so, at UnivJobs' sole discretion.

3.)**Listing Employment or Contracting Opportunities**. Upon registration, a Business may submit, through our Services, a notification to Students of a potential employment or contracting opportunity (a “Job Posting”). A Job Posting may only notify Students of a single employment or contracting opportunity, and must include, at a minimum, the following information: start date, position title and job description. Upon submission of a Job Posting, the submitting Business may fix typographical errors within the Job Posting, but may not make any substantial changes to the Job Posting. UnivJobs may also fix typographical errors within the Job Posting, but is not obligated to.

You agree not to use our Services to promote or further the commercial activities, including by submitting a Job Posting in connection with those activities, of any of the businesses, activities, or practices set forth in UnivJobs list of Prohibited Business, as incorporated into these Terms by reference as if set forth fully herein. For avoidance of doubt, each Job Posting must comply with all restrictions hereunder, including those governing the submission of User Content and general use of our Services. UnivJobs may, but is not obligated to, make an independent investigation of the Job Posting to ensure full compliance with these Terms. If UnivJobs determines, in its sole discretion, that any representation or warranty made by you pursuant to these Terms is in any way false, incomplete, or inaccurate, UnivJobs may, at any time, reject, remove, or suspend or delay the posting of your Job Posting, in whole or in part. UnivJobs may, but is not obligated to, provide you with an explanation for the rejection or removal of any of your Job Postings from our Services.

All jobs posted on UnivJobs will be automatically transferred into a publicly-viewable job listing page. These pages are indexed to various third parties, and are not taken down after being filled; however, the job page will not accept applicants once a listing is closed (and the page will act as informational only, with links bringing a user back to the UnivJobs default homepages.)

4.)**Privacy**. It is important that you read and understand the Privacy Policy, especially because the nature of the Services necessarily involve the collection and use of personally identifiable information and other personal data (‘Personal Data’). The most current Privacy Policy will apply to any and all use of the Services. UnivJobs will not intentionally edit, modify, delete or disclose the contents of your Personal Data in connection with the Services except (a) as reasonably necessary for UnivJobs (or its service providers) to provide the Services, including processing and responding to your inputs, (b) to communicate with you, (c) as otherwise permitted under the Privacy Policy or elsewhere in these Terms, (d) when UnivJobs reasonably believes that such action is necessary to conform or comply with any legal, regulatory, law enforcement or similar requirement or investigation, to protect or defend the rights or property of UnivJobs or any third party or to enforce the Terms or (e) as otherwise authorized by you.

5.)**Payment.**  Some of our Services, including the opportunity for a Business to post an employment opportunity, will be available for purchase. You are responsible for all charges incurred under your account, whether made by you or another person using your account. If for any reason UnivJobs does not receive payment for a purchase, UnivJobs may exercise its rights in law and equity, including (a) immediately suspending or terminating your account; (b) seeking collection of the outstanding amount owed; and/or (c) seeking legal action against you for the breach of these Terms. You are also responsible for paying any governmental taxes imposed in connection with use or purchase of any of our Services, including sales, use, and excise taxes (excluding only taxes on UnivJobs net income). To the extent that UnivJobs is obligated to collect such taxes, the applicable tax will be added to your billing account. All sales are final. UnivJobs is not responsible for any costs or expenses in connection with any interactions between Students and Businesses.

6.)**Proprietary Rights.** Unless UnivJobs explicitly states otherwise in an agreement between you and UnivJobs, as between you and UnivJobs, UnivJobs owns or licenses and retains all rights,title and interests in and to all Apps, data, content, graphics, forms, artwork, images, photographs, functional components and any software concepts and documentation and other material on, in or made available through our Services (“Services Materials”), as well as the selection, coordination, arrangement, and organization and enhancement of the Services Materials. All Services Materials are protected pursuant to copyright, trademark, patent and other applicable laws. As between any user of the Services and UnivJobs, all names, trademarks, service marks, certification marks, symbols, slogans or logos appearing on the Services are proprietary to UnivJobs or its affiliates, licensors (including Businesses), or suppliers. Use or misuse of these trademarks is expressly prohibited and may violate federal and state trademark law. Under no circumstances will you have any rights of any kind in or to the Services Materials, other than the right to use the Services Materials in accordance with these Terms.

Using our Services does not give you ownership of any intellectual property rights in our Services or the content you access. You may not use content from our Services unless you obtain permission from its owner or are otherwise permitted by law. These terms do not grant you the right to use any branding or logos used in our Services.

Certain features of the Services (including the registration processes described in Section 1 above) may allow you to contribute comments, feedback, information, content, text, files, trademarks, logos, graphics, postings, and other materials and information, including Job Postings, for access, use, viewing and commentary by other users to the Services (“User Content”). By posting User Content, you represent that you have the full legal right to provide the User Content and that use of the User Content by our Services and all other persons and entities will not: (a) infringe any intellectual property rights of any person or entity or any rights of publicity, personality, or privacy of any person or entity, including as a result of your failure to obtain consent to post personally identifying or otherwise private information about a person; (b) violate any law, statute, ordinance, regulation, or agreement; (c) be defamatory, libelous or trade libelous, unlawfully threatening, or unlawfully harassing; (d) impersonate any person or entity or falsely state or otherwise imply an affiliate with a person or entity, including any business or educational institution, or that is generally false, deceptive, misleading, deceitful, misinformative, or constitutes a “bait and switch”; (e) be obscene, pornographic, or indecent; (f) violate any community or Internet standard; (g) constitute misappropriation of any trade secret or know-how; or (h) constitute disclosure of any confidential information owned by any third party.

You retain all right, title and interest in and to the User Content that you submit and all intellectual property rights embodied therein. Upon your submission of User Content or other material or information to UnivJobs, you grant UnivJobs a worldwide, perpetual, irrevocable, transferable, license to access, use, distribute, reproduce, display, modify, host, communicate, publish, publicly perform, publicly distribute, and create derivative works based upon, and sublicense, the User Content, all without any compensation to you whatsoever. This license continues even if you stop using our Services. If you believe that any content or postings on our Services or the Application violate your intellectual property or other rights, please follow our Complaint Procedure in Section 12 of these Terms.

Unauthorized Activities. You agree that you will not use our Services for: (a) any illegal or unauthorized purposes that violate any local, national, or international laws (including but not limited to import, export, copyright, trademark and employment anti-discrimination laws); (b) contacting any other user of our Services who has requested not to be contacted; (c) stalking or harassing anyone; (d) data mining, scraping, or for releasing spiders, robots, web crawlers, or any other data gathering or extraction tools to collect any information from our Services, including any information related to the Job Postings, except to the extent our Services are indexed by general purpose public search engines; (e) promoting any effort to compete with UnivJobs, including using our Services to provide, alone or in combination with any other product or service, any service to any third party or any use that causes a reduction or loss of business for UnivJobs as related to an existing or potential customer; (f) modifying, copying, distributing, displaying, performing, reproducing, publishing, licensing, creating derivative works from, transferring, selling any of our Services Materials, unless otherwise authorized by these Terms or in a separate written agreement with UnivJobs; (g) attempting to gain unauthorized access to UnivJobs' computer system or engaging in any activity that interferes with the performance of, or impairs the functionality of our Services; (h) any resale or commercial use of our Services, the Services Materials, or the User Content; (i) using our Services to access or collect any personally identifiable information, including any names, email addresses or other such information for any purpose, including any commercial purposes; (j) violating or offending any community or Internet standards of decency; or (k) removing, circumventing, disabling, damaging or otherwise interfering in any way with any security features of our Services aimed at preventing or restricting the unauthorized use of our Services or any of the Services Materials. You may only use our Services and the Services Materials consistently with these Terms. A Business may use our Services to create and maintain a culture of workplace diversity and inclusion and it may not use our Services to unlawfully discriminate against any Student. Any other use of our Services or Services Materials, including but not limited to the aforementioned unauthorized uses, without prior written permission of UnivJobs is strictly prohibited. You acknowledge and agree that the unauthorized use of our Services or the Services Materials could cause irreparable harm to UnivJobs and that in the event of such unauthorized use, UnivJobs shall be entitled to an injunction in addition to any other remedies available at law or in equity.
Third Party Web Sites and Content. Our Services are available for informational purposes only. UnivJobs is a private company, and is not affiliated with any Business or educational institution, including any university or college. Our Services may contain links to other Internet Web sites for the convenience of users in locating information, products, or services that may be of interest. Our Services may also incorporate features and services provided by third parties, such as payment processing. Use of such third party links, features, and services, our Services and the Services Materials, and any other material or content on and made available through our Services is entirely at your own risk. UnivJobs does not recommend and expressly disclaims any responsibility for the content, the accuracy of the information, or quality of products or services provided by or advertised on third party sites or the transactions you conduct or enter into with third parties. Your use of any third party’s website is at your own risk, and subject to the terms and conditions of such other websites, including the terms and conditions of UnivJobs third party payment processors. UnivJobs does not endorse any product, service, or treatment provided on a third party website or advertised or provided on our Services.
Availability of the Services. UnivJobs uses reasonable efforts to ensure that our Services are generally available. However, there will be occasions when access to our Services will be interrupted or unavailable. UnivJobs will use reasonable efforts to minimize such disruption where it is within its reasonable control. You agree that UnivJobs shall not be liable for any modification, suspension, or discontinuance of our Services and that all amounts paid under these Terms are non-refundable. In addition, UnivJobs may update, modify, suspend or terminate the Services, in whole or in part, at any time.
Disclaimer. The information on our Services is for informational purposes only. Without limiting anything else in these Terms or otherwise, UnivJobs is not responsible for any errors or omissions in our Services or the Services Materials. UnivJobs, its subsidiaries, and affiliates, are not responsible for and do not guarantee the accuracy or completeness of any Services Materials, User Content, products, data, services (whether performed by UnivJobs, any Student or Business, or any third party), links, advertisements, or other items contained within our Services. UnivJobs reserves the right to immediately remove any Services Materials or User Content for any reason or for no reason. UnivJobs cannot and does not review all communications or products made available on or through our Services, but, although not obligated to, may review, verify, make changes to or remove any User Content, Services Materials, the products or services made available in connection with our Services, including information submitted in connection with the Services Materials or other features at any time, with or without notice in its sole discretion.
 THE SERVICES MATERIALS, USER CONTENT, SERVICES, PRODUCTS, INFORMATION, AND OTHER MATERIALS ON, IN AND MADE AVAILABLE THROUGH OUR SERVICES ARE MADE AVAILABLE “AS IS” AND “WITH ALL FAULTS.” USE OF OUR SERVICES IS ENTIRELY AT YOUR OWN RISK. UNIVJOBS AND ITS LICENSORS MAKE NO REPRESENTATIONS OR WARRANTIES, AND DISCLAIM ALL REPRESENTATIONS AND WARRANTIES, WITH RESPECT TO THE USER CONTENT, THE SERVICES MATERIALS, SERVICES, PRODUCTS, DATA AND OTHER MATERIALS ON, IN AND MADE AVAILABLE THROUGH OUR SERVICES, EXPRESS OR IMPLIED, WRITTEN OR ORAL, ARISING FROM COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE, OR OTHERWISE, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, SYSTEMS INTEGRATION, NON-INTERFERENCE, QUALITY, TITLE, AND NON-INFRINGEMENT. THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY, COMPLETENESS AND EFFORT WITH REGARD TO ANY USER CONTENT, THE SERVICES MATERIALS, SERVICES, PRODUCTS, DATA AND OTHER MATERIALS ON, IN AND MADE AVAILABLE THROUGH OUR SERVICES, IS WITH YOU.
LIMITATION OF LIABILITY. UNIVJOBS AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, EXTRA-CONTRACTUAL, OR PUNITIVE DAMAGES OF ANY KIND WHATSOEVER, INCLUDING LOST REVENUES OR LOST PROFITS, WHICH MAY OR DOES RESULT FROM THE USE OF, ACCESS TO, OR INABILITY TO USE THE USER CONTENT, THE SERVICES MATERIALS, SERVICES, PRODUCTS, DATA AND OTHER MATERIALS ON, IN AND MADE AVAILABLE THROUGH OUR SERVICES, REGARDLESS OF LEGAL THEORY, WHETHER OR NOT YOU OR UNIVJOBS HAD BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES, AND EVEN IF THE REMEDIES OTHERWISE AVAILABLE FAIL OF THEIR ESSENTIAL PURPOSE. UNDER NO CIRCUMSTANCES WILL THE TOTAL LIABILITY OF UNIVJOBS AND ITS LICENSORS TO YOU OR ANY OTHER PERSON OR ENTITY IN CONNECTION WITH, BASED UPON, OR ARISING FROM THE USER CONTENT, THE SERVICES MATERIALS ON, IN AND MADE AVAILABLE THROUGH OUR SERVICES, PRODUCTS, DATA OR OTHER MATERIALS OFFERED IN CONNECTION THEREWITH EXCEED THE PRICE PAID BY YOU DURING THE PRECEDING YEAR FOR USE OF THE SERVICES AND PRODUCTS. SOME STATES DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IF ANY PART OF THIS LIMITATION ON LIABILITY IS FOUND TO BE INVALID OR UNENFORCEABLE FOR ANY REASON, THEN THE TOTAL LIABILITY OF UNIVJOBS AND ITS LICENSORS SHALL NOT EXCEED TEN DOLLARS ($10). If you are dissatisfied with our Services or with any of these Terms, or feel UnivJobs has breached these Terms, your sole and exclusive remedy is to discontinue using the Services.
Indemnification. You shall indemnify UnivJobs and its directors, officers, employees, agents, contractors and licensors (“UnivJobs Indemnitees”) against all claims, actions, suits, and other proceedings (each, a “Claim”) arising out of or incurred in connection with our Services and your use of our Services, the Services Materials or any services, product or data obtained through our Services, your fraud, violation of law, negligence, willful misconduct, or any other use of our Services, the User Content, the Services Materials, the services, products, information and other materials on, in and made available through our Services, except to the extent attributable to UnivJobs, or any breach by you of these Terms and shall indemnify and hold UnivJobs Indemnitees harmless from and against all judgments, losses, liabilities, damages, costs, and expenses (including reasonable attorneys’ fees and attorneys’ disbursements) arising out of or incurred in connection with such Claims. You may not settle any Claim without the prior written consent of UnivJobs. UnivJobs or its licensors may assume the defense of any Claim, at your sole cost and expense, and you shall cooperate in all reasonable respects in such defense. You shall have the right to employ separate counsel in any Claim and to participate in the defense thereof. If UnivJobs or its licensors do not notify you that it elects to undertake the defense thereof, you shall have the right to defend the Claim with counsel reasonably acceptable to UnivJobs, subject to the right of UnivJobs to assume, at our sole cost and expense, the defense of any Claim at any time prior to the settlement or final determination thereof.
Complaint Procedures. If you believe that any content or postings on our Services violates your intellectual property or other rights, please notify UnivJobs by email at univjobs@gmail.com a comprehensive detailed message setting forth the following information: (a) your name and the name of your company, if any; (b) your contact information, including your email address; (c) the nature and substance of your complaint, the specific rights at issue, and your basis for making the complaint, including the content or posting that is objectionable; and (d) the following statement: “The statements, representations, and assertions made in this message are true, complete, and accurate and I have the full legal authority to make each and every such statement, representation, and assertion and to make and be granted any demand made in this message.”
Termination. UnivJobs may immediately terminate your access to all or any part of the Services (including without limitation, any App) at any time, with or without cause, with or without notice. 

If you elect to terminate your registration and Services account, you may do so at any time by sending an email (that includes your email address) to univjobs@gmail.com or by going to your account settings and choosing “suspend account.” Please be advised that your Services account is not terminated simply by deleting our App from your mobile device. Your registration and Services account can only be terminated by following the process described above in this provision. 

Upon any termination, all rights and obligations of the parties under these Terms shall cease, and you shall immediately stop accessing and using the Services, except that (a) all obligations that accrued prior to the effective date of termination (including payment obligations, if any) and all remedies for breach of these Terms shall survive, (b) UnivJobs may retain and use User Content and other data and business records resulting from your use of the Services (but not in a manner that discloses your identity) and (c) the provisions of those sections of these Terms that should reasonably be understood to continue in effect shall survive (including without limitation, the sections entitled Proprietary Rights, No Warranties and Disclaimer, Limitation of Liability, Indemnification, and Governing Law and Jurisdiction.
Channel Partner Teams. The term “Channel Partner” means any distribution platform operator or other third party who is authorized to make our Apps available for distribution pursuant to arrangements with UnivJobs. Currently, the only Channel Partners are Apple Inc. for iOS devices via the App Store, and Google Inc. for Android devices via Google Play. In the event that you obtain an App from one of our Channel Partners, then the following shall apply: 

If you elect to terminate your registration and Services account, you may do so at any time by sending an email (that includes your email address) to univjobs@gmail.com or by going to your account settings and choosing “suspend account.” Please be advised that your Services account is not terminated simply by deleting our App from your mobile device. Your registration and Services account can only be terminated by following the process described above in this provision. 

Both you and UnivJobs acknowledge that the agreements in these Terms are concluded between you and UnivJobs only, and not with any Channel Partner, and that the Channel Partner is not responsible for the App or any content;

You will only use the App in connection with a device that you own or control;

You acknowledge and agree that the Channel Partner has no obligation whatsoever to furnish any maintenance and support services with respect to the App;

In the event of any failure of the App to conform to any applicable warranty, including those implied by law, you may notify the applicable Channel Partner of such failure; upon notification, their sole warranty obligation to you will be to refund to you the purchase price, if any, paid for the App;

You acknowledge and agree that UnivJobs, and not the Channel Partner, is responsible for addressing any claims you or any third party may have in relation to the App;

You acknowledge and agree that, in the event of any third party claim that the App or your possession and use of the App infringes that third party's intellectual property rights, UnivJobs, and not the Channel Partner, will be responsible for the investigation, defense, settlement and discharge of any such infringement claim;

You represent and warrant that you are not located in a country subject to a Canadian Government embargo, or that has been designated by the Canadian Government as a “terrorist supporting” country, and that you are not listed on any Canadian government list of prohibited or restricted parties;

Both you and UnivJobs acknowledge and agree that, in using the App and content, you will comply with any applicable third party terms of agreement which may affect or be affected by such use;

Both you and UnivJobs acknowledge and agree that the applicable Channel Partner and its subsidiaries are third party beneficiaries of these Terms, and that upon your acceptance of these Terms, the applicable Channel Partner will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third party beneficiary hereof; and

In the event you use the App to provide you with real-time route guidance, YOUR USE OF THIS REAL TIME ROUTE GUIDANCE APPLICATION IS AT YOUR SOLE RISK. LOCATION DATA MAY NOT BE ACCURATE.

Changes to these Terms. UnivJobs reserves the right at any time to modify, alter, or update these Terms. Your use of our Services following any changes means that you agree to follow and be bound by the terms as changed. Any change to these Terms shall be effective as to any visitor who has visited our Services before the change was made. It is the obligation of users using our Services before the change to learn of changes to the Terms since their last visit. UnivJobs may suspend or terminate your account and/or your ability to use our Services, for failure to comply with these Terms, for inactivity on our Services, for providing UnivJobs with untrue or inaccurate information about yourself, for infringement upon UnivJobs proprietary rights, or for any other reason whatsoever or for no reason.
Relationship Between the Parties. Nothing in these Terms shall be construed as making either party the partner, joint venturer, agent, legal representative, employer, contractor, or employee of the other.
Governing Law and Jurisdiction. These Terms represent the entire agreement between you and UnivJobs with respect to the subject matter hereof, and supersede all prior and contemporaneous written and oral representations, understandings, and agreements, express and implied, and will be governed by and construed in accordance with the laws of the province of Ontario, without reference to its conflict of law rules; PROVIDED, HOWEVER, THAT THE TERMS OF ANY APPLICABLE LAW NOW OR HEREAFTER ENACTED THAT IS BASED ON, DERIVED FROM, SIMILAR TO, OR CONNECTED WITH THE UNIFORM COMPUTER INFORMATION TRANSACTIONS ACT DRAFTED BY THE NATIONAL CONFERENCE OF COMMISSIONERS ON UNIFORM STATE LAWS SHALL NOT APPLY EXCEPT TO THE EXTENT THAT THE LAW EXPRESSLY PROHIBITS ALTERATION BY THESE TERMS OF THE APPLICABILITY OF ONE OR MORE SECTIONS OF THE LAW. By accessing, viewing, or using the services, works, content, or materials on our Services, you consent and agree to (a) the exclusive jurisdiction of the federal and state courts located in the Ontario, Canada province (b) accept service of process by personal delivery or mail; and (c) irrevocably waive the right to trial by jury and any jurisdictional and venue defenses otherwise available. 

A printed version of these Terms and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms (including any Policy) to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. You and UnivJobs agree that any claim or cause of action arising out of or related to the Services must be commenced within 1 year after the claim or cause of action arose. Otherwise, such claim or cause of action is permanently barred. 

ANY ACTION OR PROCEEDING UNDER THESE TERMS WILL TAKE PLACE ONLY ON AN INDIVIDUAL BASIS; CLASS ACTIONS AND PROCEEDINGS ARE NOT PERMITTED. YOU UNDERSTAND AND AGREE THAT BY ENTERING INTO THESE TERMS, YOU AND UNIVJOBS ARE EACH WAIVING THE RIGHT TO TRIAL BY JURY AND TO PARTICIPATE IN A CLASS ACTION.
Miscellaneous. Our Services are controlled and operated from within the Canada. Without limiting anything else, UnivJobs makes no representation that our Services, Services Materials, User Content, services, products, information or other materials available on, in, or through our Services is appropriate or available for use in other locations, and access to them from territories where they are illegal is prohibited. Those who choose to access our Services from other locations do so on their own volition and are responsible for compliance with applicable laws. The waiver or failure of UnivJobs to exercise in any respect any right provided hereunder shall not be deemed a waiver of such right in the future or a waiver of any of other rights established under these Terms.
 Headings used in these Terms are for reference only and shall not affect the interpretation of these Terms. No person or entity not party to this agreement will be deemed to be a third party beneficiary of these Terms or any provision hereof. When used herein, the words “includes” and “including” and their syntactical variations shall be deemed followed by the words “without limitation.”
If you have any questions or need to contact us, we recommend you reach out to univjobs@gmail.com . If your question is urgent, you may contact 647-779-8525
Last modified: June 29, 2016
Copyright © 2017 DCommons, Inc.; All rights reserved.

**Comment by charlesjavelona** [comment]
PRIVACY POLICY
Welcome to UnivJobs, operated by DCommons, Inc. (“UnivJobs” and sometimes referred to as “our”) and located at 2035 Sunset Lake RoadSuite B-2, 19702, Newark, Delaware.  This Privacy Policy addresses UnivJobs' practices regarding information collected from users and visitors of our Services and only addresses information collected directly through or from our Services – it does not address or govern any information-gathering, use, or dissemination practices related to information collected from the visitor (sometimes referred to as a “visitor,” "you" or "your") other than directly through or from our Services, such as from telephone, facsimile, postal mail, personal delivery, or other or additional offline means or media.
This Privacy Policy is incorporated into UnivJobs Terms and Conditions by reference, as if set forth fully therein, which must be reviewed and accepted by you. Our Services are not intended for children under the age of 18. UnivJobs does not knowingly collect personal information online from visitors in this age group.
Collection of Personal Information from Services Visitors.  In addition to other collection methods specifically set forth herein, UnivJobs may collect: (a) the email addresses of users that communicate with UnivJobs via email; and (b) information knowingly provided by the user through our Services in informational sections, including any contact, registration, or application forms. UnivJobs may also use Internet cookies and other identifiers or methods of web analysis to gather, store, and track certain information related to your visit to and activity on our Services. If you are uncomfortable with the idea of your information being used in this way, most computer systems and web browsers offer privacy settings and options, such as disabling cookies or opting for “Do Not Track” features. UnivJobs does not override these settings or options, and encourages you to use them to enhance your choices and personalize your experiences. However, in order to access certain content, features, services, products or benefits on our Services, you may be required to provide UnivJobs with certain information, including some types of personally identifying information such as your email, educational institution, business affiliation, address, and phone number. If you do not wish to provide such information through our Services or if you opt to utilize the aforementioned privacy features of your computer system or web browser, you may not be able to obtain certain content, features, services, products or benefits of our Services.
Use of Personal Information Collected.  Personal information collected by UnivJobs may be used by UnivJobs for limited purposes, including recordkeeping, editorial and feedback purposes, content improvement, or to customize the content and layout of our Services. Personally identifying information, such as names, postal and email addresses, phone numbers, and other personal information voluntarily provided to UnivJobs may be added to UnivJobs' databses and used for future contact regarding updates to our Services or new services provided by UnivJobs. From time to time, UnivJobs may need to contact you regarding information you submitted to UnivJobs. You agree that UnivJobs may use your personal information for such contact with you. UnivJobs may also desire to contact you for market research purposes or to provide you with marketing information that UnivJobs believes would be of particular interest. You will have the option of not being contacted by UnivJobs and opting-out of such contacts by selecting the opt-out option in your profile. You may also opt-out from receiving certain messages in the manner set forth below.
Disclosure of Personal Information to Third parties.  Except as specifically set forth herein, any personally-identifying information that you provide to UnivJobs through our Services will not be disclosed to third parties not affiliated with UnivJobs. Notwithstanding the foregoing, any information you submit to UnivJobs, including any personally-identifying information you include in your personal profile with our Services, may be viewed and accessed by others, and may be indexed and displayed through our Services’s internal search engines and other publicly accessible search engines. Your personally-identifying information may also be disclosed to third parties in order to verify that information, including by contacting your educational institution or business affiliation, and in order to provide you with the services requested through our Services, including to third party payment processors for the processing of payments. Personally-identifying information may be used by UnivJobs approved third party vendors to assist UnivJobs in providing, improving, analyzing, and securing our Services. Identifying and non-identifying user information and data may also be disclosed or distributed to a third party with which UnivJobs enters or reasonably may enter into a corporate transaction, such as, for example, a merger, consolidation, acquisition, or asset purchase, or to a third party pursuant to a subpoena, court order, or other form of legal process, in response to a request by or on behalf of any local, state, federal, or other government agency, department, or body, whether or not pursuant to a subpoena, court order, or other form of legal process, or if determined by UnivJobs in its sole judgment that such disclosure or distribution is appropriate to protect the life, health, or property of UnivJobs or any other person or entity. In addition, identifying and non-identifying user information and data may be provided to third parties that contract with UnivJobs to provide products, information, or other services that UnivJobs believes that visitors to our Services may be interested in obtaining. While UnivJobs may undertake efforts to see that any third party to which UnivJobs discloses personally-identifying information is under an obligation to use the personal information solely for the purposes for which the information was disclosed, such third parties are independent third parties over which UnivJoobs exercises no control. UnivJobs is not responsible for, and will not be liable for, the conduct, actions, omissions, or information handling or dissemination practices of third parties.
Links to Other Services. Our Services may also contain links to third party websites. Our Services may contain links to other Internet websites for the convenience of users in locating information, products, or services that may be of interest. If you access a third party website from a link on our Services, any information you disclose on that website is not subject to this Privacy Policy. It is possible that these links may be used by third parties or others to collect personal or other information about you. UnivJobs is not responsible for the privacy practices of such websites, advertisers, or third parties or the content of such websites and it is your sole obligation to review and understand the privacy practices and policies of these other websites. UnivJobs does not control these third parties’ use of cookies, collection of information, or how they manage such information. It is solely your obligation to review and understand the privacy practices and policies of these other websites, advertisers and any third parties.
Comments and User Content.  All materials or comments posted to public areas of our Services are public. Please refer to the Terms and Conditions for further details concerning User Content and other materials submitted to our Services. As such, UnivJobs assumes no liability for the accuracy of such information, no duty to update or correct such information, and no liability for such communications arising under the laws of copyright, libel, privacy, obscenity, or otherwise.
Security Measures and Communicating with UnivJobs.  Please be advised that the security and confidentiality of any communication or material transmitted through the Internet or any wireless network, including via our Services, email or text messages, cannot be and is not guaranteed. You acknowledge that the technical processing and transmission of our Services’ content may be transferred unencrypted and may involve: (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Accordingly, UnivJobs is not responsible for the security of information transmitted via the Internet or any wireless network.
Access to and Ability to Correct Personal Information; Opt-Out Right.  Upon your request, UnivJobs will provide you with a summary of any personally-identifying information retained by UnivJobs that has been voluntarily provided by you to UnivJobs through email, contact forms, or other online avenues. You may modify, correct, change, or update this information by contacting UnivJobs at the email address set forth below. In addition, except as necessary to obtain the services or information requested through our Services, you may opt out of having your personally-identifying information prospectively retained by UnivJobs by contacting UnivJobs at the email address set forth below. This provision does not apply to collection of through the standard data tracking features of our Services, such as Internet cookies and other identifiers or methods of web analysis, or to any other information that does not meet the description hereunder. As set forth above, many computer systems and web browsers offer privacy settings and options that may allow you to opt-out of some of these data tracking and collection methods. 

If you wish to opt-out of receiving promotional emails at any time, please click the “unsubscribe” link at the bottom of the email. 

You may also opt-out from receiving further text messages by: texting STOP, UNSUBSCRIBE or CANCEL in response to our text message; by emailing your request to us at univjobs@gmail.com or by calling us at the phone number listed below. 

Please also be advised that your desire to opt-out of future communications will not be effective (nor will your Services registration or account be terminated) simply by deleting our App from your mobile device. Opting-out from promotional emails becomes effective only by following the process described above. Your Services registration and account can only be terminated by following the procedures described in UnivJobs Terms and Conditions.
California Residents.  Under California Civil Code Section 1798.83 (the “Shine the Light” law), California residents who provide personal information in obtaining products or services from UnivJobs are entitled to request and obtain from us once per calendar year information about the customer information about them that we have shared, if any, with other businesses for their own direct marketing uses. If applicable, this information would include the categories of customer information and the names and addresses of those businesses with which we shared customer information for the immediately prior calendar year (e.g., requests made in 2018 will receive information regarding 2017 sharing activities). If you are a California resident and would like a copy of this information, please submit a written request to: 

DCommons, Inc.
Attn: California/Shine the Light
2035 Sunset Lake RoadSuite B-2, 
19702, Newark, Delaware.

Right to Change Privacy Policy.  UnivJobs reserves the right at any time to modify, alter or update this Privacy Policy. Your use of our Services following any changes means that you agree to follow and be bound by the Privacy Policy as changed. Any change to this Privacy Policy shall be effective as to any visitor who has visited our Services before the change was made. It is the obligation of users visiting our Services before the change to learn of changes to the Privacy Policy since their last visit.

If you have any questions or need to contact us, we recommend you reach out to univjobs@gmail.com. If your question is urgent, you may contact 647-779-8525

Last modified: June 29, 2016
Copyright © 2017 DCommons, Inc.; All rights reserved.

**Comment by charlesjavelona** [comment]
Please see signup for student and employers or root_url/privacy  : root_url/terms
